### ISSUE TITLE
How to get rid of top header that is 100px tall

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.templates#47]
I found that style brand-header has 100px height and it is not possible to remove it with any option. 
`.brand-header {
    height: 100px;
}`
and there is following div
`<div class="fixed-top container-fluid brand-header bg-white">`

Is it intentional?

**Comment by joeaudette** [comment]
As I mentioned when we added features in cloudscribe core for editable header and footer and drag/drop a site logo, those features pretty much blew up the layouts of all the themes.

The options I considered were:
1. hide those features by default so they are not seen in site settings page unless you enable them and are willing to make changes in the themes to accommodate them.
2. try to make change myself in all themes to make them work at least reasonably if logo and header and footer content is used.

I went with option 2 but it was not an easy problem to solve and I did not solve it perfectly, but itworks reasonably.

The technical css problem is that the themes all used fixed top navbar headers. That uses absolute positioning. If you know about CSS absolute positioning, it removes those elements from the flow of the page and that means you have to make space for something fixed at the top by adding top padding to the body otherwise that absolute positioned stuff obscures other elements. 
In other words if the header content grows it obscures the breadcrumbs and content below so it needs to be fixed height and it needs body top padding equivalent to its height.

So 100px seemed enough to get a site logo and one line of header text to work reasonably in the themes we ship, but it can still blow up the layout if you add too much header content. 

It was time consuming to go through each of the bootswatch themes and make those changes and I did the best I could. I don't really consider myself a web designer, I'm a developer.

This is an open source project and if anyone thinks they can do a better job with the included themes I would welcome the help for someone else to take over maintaining the themes that are shipped in the project template. Sometimes I think I should just remove the bootswatch themes from the template and setup a repo for community themes that people can download separately.

**Comment by cheverdyukv** [comment]
Thank you for explanation. I did realize today that there is absolution positioning after I was trying to remove that header. I'm also not web designer so at the end I had to compare with previous version to fix it properly everywhere.
