### ISSUE TITLE
cloudscribe add-in for Visual Studio for Mac

### ISSUE THREAD

**Issue by trendoid** [cloudscribe/cloudscribe.templates#50]
I didn't see any cloudscribe Templates add-in when searching in Visual Studio for Mac 2019.  Is that coming soon?  Need help with that?

![image](https://user-images.githubusercontent.com/7746539/59433233-0ee60d00-8db7-11e9-9da0-48df29f60da1.png)

https://docs.microsoft.com/en-us/visualstudio/mac/extending-visual-studio-mac-walkthrough?view=vsmac-2019

http://addins.monodevelop.com/

**Comment by joeaudette** [comment]
@trendoid building a plugin for VS Mac is not a priority for me. We have a plugin for VS2017 and VS2019, but it has to be [installed from the marketplace](https://marketplace.visualstudio.com/items?itemName=joeaudette.cloudscribeProjectTemplate), it doesn't just show up in VS automagically. Hopefully someday Microsoft will unify VS and VS Mac so that the same plugins work in both. 

We also have a template that works from the command line with dotnet new command as discussed [here](https://www.cloudscribe.com/introduction) which can be used on any .net core supported platform, so that would be what I would use on Mac or Linux.

**Comment by trendoid** [comment]
@joeaudette Thanks.  I'll take a look at that CLI command.
